import { pgEnum } from 'drizzle-orm/pg-core'
import { AdoptionStatusValues } from './adoption-status'
import { AnimalHistoryTypeValues } from './animal-history-type'
import { AnimalStatusValues } from './animal-status'
import { AppointmentStatusValues } from './appointment-status'
import { CampaignStatusValues } from './campaign-status'
import { ConsultationTypeValues } from './consultation-type'
import { HealthConditionValues } from './health-condition'
import { ProcedureCategoryValues } from './procedure-category'
import { ProcedureStatusValues } from './procedure-status'
import { ProfileTypeValues } from './profile-type'
import { SexValues } from './sex'
import { SizeValues } from './size'
import { SpeciesValues } from './species'
import { TransactionCategoryValues } from './transaction-category'
import { TransactionStatusValues } from './transaction-status'
import { UrgencyLevelValues } from './urgency-level'

export const profileTypeEnum = pgEnum('profile_type', ProfileTypeValues)
export const procedureCategoryEnum = pgEnum('procedure_category', ProcedureCategoryValues)
export const transactionCategoryEnum = pgEnum('transaction_category', TransactionCategoryValues)
export const urgencyLevelEnum = pgEnum('urgency_level', UrgencyLevelValues)
export const speciesEnum = pgEnum('species', SpeciesValues)
export const sizeEnum = pgEnum('size', SizeValues)
export const sexEnum = pgEnum('sex', SexValues)
export const healthConditionEnum = pgEnum('health_condition', HealthConditionValues)
export const animalStatusEnum = pgEnum('animal_status', AnimalStatusValues)
export const campaignStatusEnum = pgEnum('campaign_status', CampaignStatusValues)
export const consultationTypeEnum = pgEnum('consultation_type', ConsultationTypeValues)
export const appointmentStatusEnum = pgEnum('appointment_status', AppointmentStatusValues)
export const procedureStatusEnum = pgEnum('procedure_status', ProcedureStatusValues)
export const adoptionStatusEnum = pgEnum('adoption_status', AdoptionStatusValues)
export const transactionStatusEnum = pgEnum('transaction_status', TransactionStatusValues)

export const animalHistoryTypeEnum = pgEnum('animal_history_type', AnimalHistoryTypeValues)
